using System.Collections.Generic;

namespace BTCPayServer.Controllers.RestApi.Models
{
    public class StoreBtcLikePaymentMethodPreviewResult
    {
        /// <summary>
        /// a list of addresses generated by the derivation scheme
        /// </summary>
        public IList<StoreBtcLikePaymentMethodPreviewResultAddressItem> Addresses { get; set; } =
            new List<StoreBtcLikePaymentMethodPreviewResultAddressItem>();

        public class StoreBtcLikePaymentMethodPreviewResultAddressItem
        {
            /// <summary>
            /// The key path relative to the account key path. 
            /// </summary>
            public string KeyPath { get; set; }
            //The address generated at the key path
            public string Address { get; set; }
        }
    }
}
